---
title: "Behavioral Experiment R Script"
author: "Patrick Jans"
date: "2026-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading the files, combining them into one dataset
all_data <- data.frame()

for (i in 1:6) {
  dat <- read.csv(paste0("subject-", i, ".csv"))
  dat$ID <- i
  all_data <- rbind(all_data, dat)
}

all_data <- all_data[, c(49, 1:48)]
practice_data <- all_data[all_data$Practice == "Yes",]
dat <- all_data[all_data$Practice == "No",]

nrow(dat[dat$RT < 20,]) # Check if there are any RT < 20, if so remove them
```

# Accuracy in block 4 for all 6 participants
```{r}
AccBlock4 <- aggregate(accuracy ~ ID, data = dat[dat$block ==4,], FUN = mean)
AccBlock4
sd(AccBlock4$accuracy)

mean(AccBlock4[AccBlock4$ID %in% c(1, 3, 5),]$accuracy) # Average accuracy block.4 of infrequent
mean(AccBlock4[AccBlock4$ID %in% c(2, 4, 6),]$accuracy) # Average accuracy block 4 of frequent readers
```

```{r}
AccBlock123 <- aggregate(accuracy ~ ID, data = dat[dat$block != 4,], FUN = mean)
AccBlock123
sd(AccBlock123$accuracy)

mean(AccBlock123[AccBlock123$ID %in% c(1, 3, 5),]$accuracy) # Average accuracy block.1-3 of infrequent
mean(AccBlock123[AccBlock123$ID %in% c(2, 4, 6),]$accuracy) # Average accuracy block 1-3 of frequent readers

AccBlock4$accuracy - AccBlock123$accuracy # difference between Block 4 accuracy and Block 1-3 accuracy
```
# Overall accuracy throughout the experiment for all 6 participants
```{r, fig.width=15, fig.height=10}
par(mfrow=c(2,3))
for (i in 1:6){
  plot(dat[dat$ID == i,]$overall_accuracy, ylim = c(0.8, 1), type = "l", xlab = "Trial",
     ylab = "Accuracy")
}
```

# Plotting the running accuracy throughout the experiment for the 6 participants
```{r, fig.width=15, fig.height=10}
par(mfrow=c(2,3))
for (i in 1:6){
  plot(dat[dat$ID == i,]$running_accuracy, ylim = c(0.65, 1), type = "l", xlab = "Trial",
     ylab = "Accuracy")
}
```

```{r}
dataBlock4 <- all_data[all_data$block == '4',]

dataBlock4$running_acc <- ave(
  dataBlock4$accuracy,
  dataBlock4$ID,
  FUN = function(x) cumsum(x) / seq_along(x)
)
```


# Plotting accuracy throughout block 4 for all participants
```{r, fig.width=15, fig.height=10}
par(mfrow=c(2,3))
for (i in 1:6){
  plot(dataBlock4[dataBlock4$ID == i,]$running_acc, ylim = c(0.85, 1), type = "l", xlab = "Trial",
     ylab = "Accuracy")
}
```

```{r}
dataBlock4$reader_group <- ifelse(
  dataBlock4$ID %in% c("1", "3", "5"),
  "Infrequent",
  "Frequent"
)

dataBlock4$Trial <- rep(1:135, times = 6)

group_accuracy <- aggregate(
  running_acc ~ reader_group + Trial,
  data = dataBlock4,
  FUN = mean
)
```

# Plotting average accuracy throughout block 4 of two groups
```{r, fig.width=5, fig.height=5}
plot( group_accuracy[group_accuracy$reader_group == "Frequent",]$Trial, group_accuracy[group_accuracy$reader_group == "Frequent",]$running_acc, ylim = c(0.88, 1), type = "l", col = "blue", xlab = "Trial", ylab = "Accuracy", main = "Average accuracy throughout block 4" ) 

lines( group_accuracy[group_accuracy$reader_group == "Infrequent",]$Trial, group_accuracy[group_accuracy$reader_group == "Infrequent",]$running_acc, col = "red" ) 

legend( "bottomright", legend = c("Frequent readers", "Infrequent readers"), col = c("blue", "red"), lty = 1 )
```


```{r, fig.width=5, fig.height=5}
dataBlock123 <- dat[dat$block != 4,]

dataBlock123$running_acc <- ave( dataBlock123$accuracy, dataBlock123$ID, FUN = function(x) cumsum(x) / seq_along(x) )

dataBlock123$reader_group <- ifelse( dataBlock123$ID %in% c(1, 3, 5), "Infrequent", "Frequent" )

dataBlock123$Trial <- rep(1:405, times = 6)

group_accuracy123 <- aggregate( running_acc ~ reader_group + Trial, data = dataBlock123, FUN = mean )

plot( group_accuracy123[group_accuracy123$reader_group == "Frequent",]$Trial, group_accuracy123[group_accuracy123$reader_group == "Frequent",]$running_acc, ylim = c(0.88, 1), type = "l", col = "blue", xlab = "Trial", ylab = "Accuracy", main = "Average accuracy throughout blocks 1-3" )

lines( group_accuracy123[group_accuracy123$reader_group == "Infrequent",]$Trial, group_accuracy123[group_accuracy123$reader_group == "Infrequent",]$running_acc, col = "red" ) 
legend( "bottomright", legend = c("Frequent readers", "Infrequent readers"), col = c("blue", "red"), lty = 1 )
```
